"""Sync schema with ORM models (safe)

Revision ID: f61dd8c176f6
Revises: 002
Create Date: 2025-11-21 19:00:50.419116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f61dd8c176f6'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_runs', 'policy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analysis_runs', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=False)

    # Use raw SQL for ARRAY to JSON conversion (requires USING clause)
    op.execute("ALTER TABLE analysis_runs ALTER COLUMN estimators TYPE JSON USING to_json(estimators)")
    op.execute("ALTER TABLE analysis_runs ALTER COLUMN feature_cols TYPE JSON USING to_json(feature_cols)")
    op.alter_column('analysis_runs', 'scenario_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'progress',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('analysis_runs', 'delta_yen',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'delta_yen_ci_low',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'delta_yen_ci_high',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_analysis_runs_status', table_name='analysis_runs')
    op.drop_index('idx_analysis_runs_tenant_id', table_name='analysis_runs')
    op.create_foreign_key(None, 'analysis_runs', 'policies', ['policy_id'], ['id'])
    op.create_foreign_key(None, 'analysis_runs', 'datasets', ['dataset_id'], ['id'])
    op.drop_column('analysis_runs', 'created_at')
    op.add_column('column_mapping_profiles', sa.Column('source_system', sa.String(), nullable=True))
    op.add_column('column_mapping_profiles', sa.Column('mapping_json', sa.JSON(), nullable=False))
    op.add_column('column_mapping_profiles', sa.Column('version', sa.String(), nullable=True))
    op.add_column('column_mapping_profiles', sa.Column('tenant_id', sa.String(), nullable=True))
    op.drop_constraint('column_mapping_profiles_name_key', 'column_mapping_profiles', type_='unique')
    op.drop_column('column_mapping_profiles', 'metadata')
    op.drop_column('column_mapping_profiles', 'mapping')
    op.drop_index('ix_datasets_created_at', table_name='datasets')
    op.alter_column('decisions', 'policy_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('decisions', 'scenario_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('decisions', 'delta_yen',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('decisions', 'delta_yen_ci_low',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decisions', 'delta_yen_ci_high',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decisions', 'delta_yen_std',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('decisions', 'verdict',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('decisions', 'quality_scores',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('decisions', 'scenario_spec',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('decisions', 'estimator_results',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('decisions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('idx_decisions_created_at', table_name='decisions')
    op.drop_index('idx_decisions_tenant_id', table_name='decisions')
    op.create_foreign_key(None, 'decisions', 'policies', ['policy_id'], ['id'])
    op.drop_column('decisions', 'risk_score')
    op.drop_column('decisions', 'confidence_score')
    op.drop_column('decisions', 'updated_at')
    op.drop_column('decisions', 'dataset_id')
    op.alter_column('diagnostics', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('diagnostics', 'model_run_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('diagnostics', 'visualization_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_diagnostics_type', table_name='diagnostics')
    op.alter_column('model_runs', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('model_runs', 'dataset_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('ix_model_runs_status', table_name='model_runs')
    op.drop_column('model_runs', 'tenant_id')
    op.drop_index('ix_policies_status', table_name='policies')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_policies_status', 'policies', ['status'], unique=False)
    op.add_column('model_runs', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_index('ix_model_runs_status', 'model_runs', ['status'], unique=False)
    op.alter_column('model_runs', 'dataset_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('model_runs', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index('ix_diagnostics_type', 'diagnostics', ['diagnostic_type'], unique=False)
    op.alter_column('diagnostics', 'visualization_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('diagnostics', 'model_run_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('diagnostics', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.add_column('decisions', sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('confidence_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('decisions', sa.Column('risk_score', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.create_index('idx_decisions_tenant_id', 'decisions', ['tenant_id'], unique=False)
    op.create_index('idx_decisions_created_at', 'decisions', ['created_at'], unique=False)
    op.alter_column('decisions', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('decisions', 'estimator_results',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decisions', 'scenario_spec',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decisions', 'quality_scores',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('decisions', 'verdict',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('decisions', 'delta_yen_std',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('decisions', 'delta_yen_ci_high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('decisions', 'delta_yen_ci_low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('decisions', 'delta_yen',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               nullable=True)
    op.alter_column('decisions', 'scenario_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('decisions', 'policy_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_datasets_created_at', 'datasets', ['created_at'], unique=False)
    op.add_column('column_mapping_profiles', sa.Column('mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('column_mapping_profiles', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint('column_mapping_profiles_name_key', 'column_mapping_profiles', ['name'])
    op.drop_column('column_mapping_profiles', 'tenant_id')
    op.drop_column('column_mapping_profiles', 'version')
    op.drop_column('column_mapping_profiles', 'mapping_json')
    op.drop_column('column_mapping_profiles', 'source_system')
    op.add_column('analysis_runs', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.drop_constraint(None, 'analysis_runs', type_='foreignkey')
    op.create_index('idx_analysis_runs_tenant_id', 'analysis_runs', ['tenant_id'], unique=False)
    op.create_index('idx_analysis_runs_status', 'analysis_runs', ['status'], unique=False)
    op.alter_column('analysis_runs', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('analysis_runs', 'delta_yen_ci_high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'delta_yen_ci_low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'delta_yen',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'progress',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('analysis_runs', 'scenario_spec',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'feature_cols',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'estimators',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('analysis_runs', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('analysis_runs', 'policy_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
