apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cqox

bases:
- ../../base

replicas:
- name: cqox-engine
  count: 5

images:
- name: cqox-engine
  newName: ghcr.io/onodera22ten/cqox-engine
  newTag: latest

configMapGenerator:
- name: cqox-config
  literals:
  - LOG_LEVEL=INFO
  - API_PREFIX=/api

secretGenerator:
- name: cqox-secrets
  envs:
  - secrets.env

patchesStrategicMerge:
- production-patch.yaml
